name: kubernetes
description: Kubernetes client for Dart/Flutter.
version: 0.0.1
homepage: https://github.com/xclud/flutter_kubernetes
repository: https://github.com/xclud/flutter_kubernetes

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.1

dev_dependencies:
  test: ^1.17.2