name: kubernetes
description: Kubernetes client for Dart/Flutter compatible with Kubernetes version 1.21.x.
version: 0.0.2
homepage: https://github.com/xclud/dart_kubernetes
repository: https://github.com/xclud/dart_kubernetes

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.1

dev_dependencies:
  test: ^1.17.2