name: kubernetes
description: A feature-rich and fully-fledged Kubernetes client for Dart/Flutter.
version: 0.1.4
homepage: https://pwa.ir
repository: https://github.com/xclud/dart_kubernetes

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4

dev_dependencies:
  test: ^1.21.4
  lints: ^2.0.0