name: kubernetes
description: A feature-rich and fully-fledged Kubernetes client for Dart/Flutter.
version: 0.1.1
homepage: https://pwa.ir
repository: https://github.com/xclud/dart_kubernetes

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.1

dev_dependencies:
  test: ^1.17.2
  flutter_lints: ^1.0.0